import { type FeatureSectionCollectionProps } from "~/components/feature-section/feature-section-collection";
import { type FeatureSectionProps } from "~/components/feature-section/feature-section";

const feature1: FeatureSectionProps = {
  description: {
    title: "Props Cheatsheets",
    subtitle: "New Daily",
    description:
      "Props cheatsheets detailing our favorite picks of the day. These will be exclusive to just our VIP members and sent out usually the night before the games or the evening of the day of the games.",
  },
  visual: { children: <h1 className="bg-blue-500">Feature 1</h1> },
};
const feature2: FeatureSectionProps = {
  description: {
    title: "PropsLab Exclusives",
    subtitle: "PrizePicks/Sleeper/Chalkboard/Underdog Slips",
    description:
      "Exclusives generated by us via our Picks provided on our Cheatsheets (Optimizing the picks and condensing them onto a slip)",
  },
  visual: { children: <h1 className="bg-blue-500">Feature 2</h1> },
};
const feature3: FeatureSectionProps = {
  description: {
    title: "Weekly Giveaways",
    subtitle: "Sports Prizes and Cash",
    description:
      "Members can have a chance to participate in weekly giveaways where they can potentially win sports prizes and even cash.",
  },
  visual: { children: <h1 className="bg-blue-500">Feature 3</h1> },
};

export const FeatureSectionCollectionData: FeatureSectionCollectionProps = {
  collection: [feature1, feature2, feature3],
};
