import { type FeatureSectionCollectionProps } from "~/components/feature-section/feature-section-collection";
import { type FeatureSectionProps } from "~/components/feature-section/feature-section";
import { Feature1 } from "~/components/feature-components/feature1";
import { Feature2 } from "~/components/feature-components/feature2";
import { Feature3 } from "~/components/feature-components/feature3";

const feature1: FeatureSectionProps = {
  description: {
    title: "Props Cheatsheets",
    subtitle: "New Daily",
    description:
      "Props cheatsheets detailing our best picks of the day. These will be exclusive to our VIP members and sent out before the games. We have 80% hitrate on our props.",
    emphasis: "80%",
    bulletPoints: ["NFL", "NBA", "NHL", "E-Sports"],
  },
  visual: { children: <Feature1 /> },
};
const feature2: FeatureSectionProps = {
  description: {
    title: "PropsLab Slips",
    subtitle: "PrizePicks/Sleeper/Chalkboard/Underdog Slips",
    description:
      "Exclusives generated by us via our Picks provided on our Cheatsheets (Optimizing the picks and condensing them onto a slip)",
    bulletPoints: [
      "PrizePicks",
      "Sleeper",
      "Chalkboard",
      "Underdog",
      "Parlay Play",
    ],
  },
  visual: { children: <Feature2 /> },
};
const feature3: FeatureSectionProps = {
  description: {
    title: "Weekly Giveaways",
    subtitle: "Sports Prizes and Cash",
    description:
      "Members can have a chance to participate in weekly giveaways where they can potentially win sports prizes and even cash.",
    bulletPoints: ["Cash Prizes", "Sports Memorabilia", "Video Games"],
  },
  visual: { children: <Feature3 /> },
};

export const FeatureSectionCollectionData: FeatureSectionCollectionProps = {
  collection: [feature1, feature2, feature3],
};
